name: linux_happiness
description: >
  A configuration manager for Linux. Currently only supports Debian derived
  distros, but other distros could be trivially supported.
version: 0.0.1-alpha
author: Dylan Powers <dylan.kyle.powers@gmail.com>
executables:
  be-happy: be_happy
dependencies:
  args: '>=0.13.7 < 0.14.0'
  yaml: '>=2.1.12 < 2.2.0'
