name: blissful
description: >
  A configuration manager for Linux. It currently only supports Debian derived
  distros, but other distros could be trivially supported.
version: 0.0.2-beta
author: Dylan Powers <dylan.kyle.powers@gmail.com>
executables:
  blissful: blissful
environment:
  sdk: ">=1.22.1"
dependencies:
  args: '>=0.13.7 <0.14.0'
  yaml: '>=2.1.12 <2.2.0'

